# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selestesearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seleste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100)),
                ('review_text', models.TextField(max_length=1500)),
                ('overall_rating', models.CharField(max_length=3)),
                ('culture_values_rating', models.CharField(max_length=3)),
                ('management_rating', models.CharField(max_length=3)),
                ('compensation_benefits_rating', models.CharField(max_length=3)),
                ('opportunities_rating', models.CharField(max_length=3)),
                ('work_life_balance_rating', models.CharField(max_length=3)),
                ('recommend_to_friend_rating', models.CharField(max_length=3)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selestesearch.Company')),
            ],
        ),
    ]
